spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/world?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema:
#      - classpath: all.sql


server:
  port: 5000
  servlet:
    context-path: /ims/web

